import { BASE, USER } from '../../core/manager.js';
import { Cell } from '../../core/table/cell.js';
import JSON5 from '../../utils/json5.min.mjs';

const STANDARD_NAMES=['当前状态表','角色状态表','背包表','当前任务与约定表','人物主表','人物发展表','历史事件表'];
const ACTION_NAMES=new Set(['insertRow','updateRow','deleteRow']);
function norm(value){return String(value??'').trim();}
function copyValue(value){if(value===undefined)return undefined;try{return structuredClone(value);}catch(_){return JSON.parse(JSON.stringify(value));}}
function copyHash(value){if(!value||typeof value!=='object')return null;try{return BASE.copyHashSheets(value);}catch(_){return copyValue(value);}}
function visiblePromptSheets(){return(BASE.getChatSheets?.()??[]).filter(sheet=>sheet?.enable).filter(sheet=>sheet?.sendToContext!==false);}
function tableNameForIndex(tableIndex){const index=Number(tableIndex);if(!Number.isInteger(index)||index<0)return null;if(index<STANDARD_NAMES.length)return STANDARD_NAMES[index];return norm(visiblePromptSheets()[index]?.name)||null;}
function sheetForIndex(tableIndex){const index=Number(tableIndex);if(!Number.isInteger(index)||index<0)return null;if(index<STANDARD_NAMES.length){const tableName=STANDARD_NAMES[index];return BASE.getChatSheets?.().find(sheet=>sheet?.name===tableName)??null;}return visiblePromptSheets()[index]??null;}
function extractCalls(text){const source=String(text??'');const calls=[];let i=0;while(i<source.length){const match=/(insertRow|updateRow|deleteRow)\s*\(/g;match.lastIndex=i;const found=match.exec(source);if(!found)break;const name=found[1];let cursor=match.lastIndex;let depth=1;let quote=null;let escaped=false;for(;cursor<source.length;cursor++){const ch=source[cursor];if(quote){if(escaped)escaped=false;else if(ch==='\\')escaped=true;else if(ch===quote)quote=null;continue;}if(ch==='"'||ch==="'"||ch==='`'){quote=ch;continue;}if(ch==='(')depth++;else if(ch===')'){depth--;if(depth===0)break;}}if(depth!==0)return{ok:false,error:`${name} 缺少右括号`,calls:[]};const argsText=source.slice(match.lastIndex,cursor);let args;try{args=JSON5.parse(`[${argsText}]`);}catch(error){return{ok:false,error:`${name} 参数无法解析：${error?.message||error}`,calls:[]};}calls.push({name,args});i=cursor+1;}return{ok:true,calls};}
function normalizeBlocks(raw){const list=Array.isArray(raw)?raw:[raw];return list.map(value=>String(value??'').replace(/^\s*<tableEdit>\s*/i,'').replace(/\s*<\/tableEdit>\s*$/i,'').replace(/^\s*<!--\s*/,'').replace(/\s*-->\s*$/,'').trim()).filter(Boolean);}
function validateAction(call){if(!ACTION_NAMES.has(call?.name))return{ok:false,error:'未知操作'};const[tableIndex,arg1,arg2]=call.args||[];const index=Number(tableIndex);if(!Number.isInteger(index)||index<0)return{ok:false,error:`${call.name} tableIndex无效`};const sheet=sheetForIndex(index);if(!sheet)return{ok:false,error:`#${index} ${tableNameForIndex(index)||'未知/不可见表'} 不存在`};const columnCount=Math.max(0,Number(sheet.getHeader?.().length)||0);const rowCount=Math.max(0,Number(sheet.getRowCount?.())-1||0);if(call.name==='insertRow'){const data=arg1;if(!data||typeof data!=='object'||Array.isArray(data))return{ok:false,error:`insertRow(${index}) data必须是对象`};for(const key of Object.keys(data)){const col=Number(key);if(!Number.isInteger(col)||col<0||col>=columnCount)return{ok:false,error:`insertRow(${index}) 列${key}越界`};}return{ok:true,action:{type:'insert',tableIndex:index,sheet,data}};}const rowIndex=Number(arg1);if(!Number.isInteger(rowIndex)||rowIndex<0||rowIndex>=rowCount)return{ok:false,error:`${call.name}(${index}) rowIndex=${arg1}越界；当前数据行数=${rowCount}`};if(call.name==='deleteRow')return{ok:true,action:{type:'delete',tableIndex:index,sheet,rowIndex}};const data=arg2;if(!data||typeof data!=='object'||Array.isArray(data))return{ok:false,error:`updateRow(${index},${rowIndex}) data必须是对象`};for(const key of Object.keys(data)){const col=Number(key);if(!Number.isInteger(col)||col<0||col>=columnCount)return{ok:false,error:`updateRow(${index},${rowIndex}) 列${key}越界`};}return{ok:true,action:{type:'update',tableIndex:index,sheet,rowIndex,data}};}
function ordered(actions){const priority={update:0,insert:1,delete:2};return[...actions].sort((a,b)=>{if(a.type==='delete'&&b.type==='delete'&&a.tableIndex===b.tableIndex)return b.rowIndex-a.rowIndex;return priority[a.type]-priority[b.type];});}
function applyAction(action){const sheet=action.sheet;if(action.type==='update'){for(const[key,value]of Object.entries(action.data)){const cell=sheet.findCellByPosition(action.rowIndex+1,Number(key)+1);if(!cell)throw new Error(`updateRow #${action.tableIndex} 找不到单元格 row=${action.rowIndex} col=${key}`);cell.newAction(Cell.CellAction.editCell,{value},false);}return;}if(action.type==='insert'){const anchor=sheet.findCellByPosition(sheet.getRowCount()-1,0);if(!anchor)throw new Error(`insertRow #${action.tableIndex} 找不到插入锚点`);anchor.newAction(Cell.CellAction.insertDownRow,{},false);const row=sheet.getCellsByRowIndex(sheet.getRowCount()-1);if(!row)throw new Error(`insertRow #${action.tableIndex} 插入后无法读取新行`);for(const[key,value]of Object.entries(action.data)){const cell=row[Number(key)+1];if(!cell)throw new Error(`insertRow #${action.tableIndex} 找不到列${key}`);cell.data.value=value;}return;}const cell=sheet.findCellByPosition(action.rowIndex+1,0);if(!cell)throw new Error(`deleteRow #${action.tableIndex} 找不到row=${action.rowIndex}`);cell.newAction(Cell.CellAction.deleteSelfRow,{},false);}
function storeSwipeSnapshot(piece){if(!piece?.hash_sheets)return;const id=Number(piece?.swipe_id);if(!Number.isInteger(id)||id<0)return;if(!Array.isArray(piece.swipe_info))piece.swipe_info=[];if(!piece.swipe_info[id]||typeof piece.swipe_info[id]!=='object')piece.swipe_info[id]={};piece.swipe_info[id].memo_hash_sheets=copyHash(piece.hash_sheets);}
export function saveMemoSnapshot(piece,sheets=BASE.getChatSheets?.()??[]){if(!piece)throw new Error('无法获取当前聊天片段，未保存');for(const sheet of sheets)sheet?.save?.(piece,true);storeSwipeSnapshot(piece);return true;}
function snapshotSheets(sheets){const snapshots=new Map();for(const sheet of sheets){const valueSheet=sheet?.getContent?.(true);if(Array.isArray(valueSheet))snapshots.set(sheet,valueSheet.map(row=>Array.isArray(row)?[...row]:row));}return snapshots;}
function rollbackSnapshots(snapshots){for(const[sheet,valueSheet]of snapshots.entries()){try{sheet.rebuildHashSheetByValueSheet(valueSheet);}catch(error){console.error('[Memo][safe-executor] 回滚表格失败',sheet?.name,error);}}}
function snapshotPieceState(piece){const id=Number(piece?.swipe_id);const info=Array.isArray(piece?.swipe_info)&&Number.isInteger(id)&&id>=0?piece.swipe_info[id]:undefined;return{hadHash:Object.prototype.hasOwnProperty.call(piece??{},'hash_sheets'),hash:copyHash(piece?.hash_sheets),swipeId:id,hadSwipeInfo:Array.isArray(piece?.swipe_info)&&Number.isInteger(id)&&id>=0&&id<piece.swipe_info.length,swipeInfo:copyValue(info)};}
function restorePieceState(piece,state){if(!piece||!state)return;if(state.hadHash)piece.hash_sheets=copyHash(state.hash);else delete piece.hash_sheets;const id=state.swipeId;if(Number.isInteger(id)&&id>=0){if(!Array.isArray(piece.swipe_info))piece.swipe_info=[];if(state.hadSwipeInfo)piece.swipe_info[id]=copyValue(state.swipeInfo);else if(id<piece.swipe_info.length)piece.swipe_info[id]=undefined;}}

export function parseMemoTableEdit(raw){const blocks=normalizeBlocks(raw);if(!blocks.length)return{ok:false,noChange:false,actions:[],error:'没有tableEdit内容'};const joined=blocks.join('\n');const noChange=/\bNO_CHANGE\b/i.test(joined);const parsed=extractCalls(joined);if(!parsed.ok)return{ok:false,noChange:false,actions:[],error:parsed.error};if(!parsed.calls.length){if(noChange)return{ok:true,noChange:true,actions:[],error:''};return{ok:false,noChange:false,actions:[],error:'没有可执行的insertRow/updateRow/deleteRow，也不是NO_CHANGE'};}const actions=[];for(const call of parsed.calls){const checked=validateAction(call);if(!checked.ok)return{ok:false,noChange:false,actions:[],error:checked.error};actions.push(checked.action);}return{ok:true,noChange:false,actions:ordered(actions),error:''};}
export function executeMemoTableEdit(raw,piece=null){const parsed=parseMemoTableEdit(raw);if(!parsed.ok)return{ok:false,changed:false,noChange:false,count:0,error:parsed.error};const targetPiece=piece||USER.getChatPiece?.()?.piece;if(!targetPiece)return{ok:false,changed:false,noChange:false,count:0,error:'无法获取当前聊天片段，未保存'};const pieceState=snapshotPieceState(targetPiece);if(parsed.noChange){try{saveMemoSnapshot(targetPiece);return{ok:true,changed:false,noChange:true,count:0,error:''};}catch(error){restorePieceState(targetPiece,pieceState);return{ok:false,changed:false,noChange:false,count:0,error:`保存NO_CHANGE快照失败：${error?.message||error}`};}}
    const touched=new Set(parsed.actions.map(action=>action.sheet));const snapshots=snapshotSheets(touched);try{for(const action of parsed.actions)applyAction(action);saveMemoSnapshot(targetPiece);return{ok:true,changed:true,noChange:false,count:parsed.actions.length,error:''};}catch(error){rollbackSnapshots(snapshots);restorePieceState(targetPiece,pieceState);return{ok:false,changed:false,noChange:false,count:0,error:error?.message||String(error)};}}
export { STANDARD_NAMES };
